language: python
python:
  - "2.7"
# command to install dependencies
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev python-h5py
  - git clone https://github.com/nanoporetech/nanonet.git
  - cd nanonet
  - sudo python setup.py install
  - cd ..
install: "python setup.py install"
# command to run tests
script: nanomod train -g /home/travis/build/scottgigante/nanomod/models/ecoli_k12_mg1655.fa -c /home/travis/build/scottgigante/nanomod/sample_data/r9/canonical -m /home/travis/build/scottgigante/nanomod/sample_data/r9/modified -t 10 -o /home/travis/build/scottgigante/nanomod/sample_data/test --nanopolish-models /home/travis/build/scottgigante/nanomod/models/nanopolish_models.fofn -vv
