language: python
python:
  - "2.7"
# command to install dependencies
sudo: required
before_install:
  - sudo add-apt-repository -qq -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y gcc-4.8 g++-4.8
  - sudo update-alternatives -qq --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo apt-get -qq install -y libhdf5-serial-dev python-h5py libblas-dev liblapack-dev libatlas-base-dev gfortran samtools parallel
  - git clone -q --recursive https://github.com/jts/nanopolish.git
  - cd nanopolish
  - make --quiet
  - export PATH=$PATH:$(pwd)
  - cd ..
  - git clone -q https://github.com/nanoporetech/nanonet.git
  - cd nanonet
  - sudo python setup.py install -q
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cd ..
  - git clone -q https://github.com/lh3/bwa.git
  - cd bwa
  - make --quiet
  - export PATH=$PATH:$(pwd)
  - cd ..
  - wget https://github.com/samtools/samtools/releases/download/1.4/samtools-1.4.tar.bz2
  - tar xf samtools-1.4.tar.bz2
  - cd samtools-1.4
  - mkdir bin && make -q && make -q prefix=bin install
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/bin
  - cd ..
install: "python setup.py install -q"
# command to run tests
script: nanomod train -g sample_data/ecoli_k12_mg1655.fa -c sample_data/r9/canonical -m sample_data/r9/modified -t 10 -o sample_data/test -vv
