language: python
python:
  - "2.7"
# command to install dependencies
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev python-h5py
  - git clone https://github.com/nanoporetech/nanonet.git
  - cd nanonet
  - sudo python setup.py install
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cd ..
  - git clone https://github.com/lh3/bwa.git
  - cd bwa
  - make
  - cd ..
install: "python setup.py install"
# command to run tests
script: nanomod train -g sample_data/ecoli_k12_mg1655.fa -c sample_data/r9/canonical -m sample_data/r9/modified -t 10 -o sample_data/test -vv
