language: python
python:
  - "2.7"
# command to install dependencies
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo apt-get -qq install -y libhdf5-serial-dev libblas-dev liblapack-dev parallel libatlas-base-dev gfortran &> /dev/null
  - pip install -q cython pysam
  - sudo apt-get -qq install -y python-h5py python-scipy python-matplotlib python-pandas &> /dev/null
  - git clone -q https://github.com/arq5x/poretools
  - cd poretools
  - pip install -q .
  - cd ..
  - which poretools &> /dev/null
  - wget -q https://github.com/samtools/samtools/releases/download/1.4/samtools-1.4.tar.bz2
  - tar xf samtools-1.4.tar.bz2
  - cd samtools-1.4
  - mkdir bin && make -s && make -s prefix=$(pwd) install
  - export PATH=$PATH:$(pwd)/bin
  - cd ..
  - which samtools &> /dev/null
  - git clone -q --recursive https://github.com/jts/nanopolish.git
  - cd nanopolish
  - make -s
  - export PATH=$PATH:$(pwd)
  - cd ..
  - which nanopolish &> /dev/null
  - git clone -q https://github.com/nanoporetech/nanonet.git
  - cd nanonet
  - sudo python setup.py -q install --no-deps &> /dev/null
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cd ..
  - which nanonettrain &> /dev/null
  - git clone -q https://github.com/lh3/bwa.git
  - cd bwa
  - make -s &> /dev/null
  - export PATH=$PATH:$(pwd)
  - cd ..
  - which bwa
install: "python setup.py -q install"
# command to run tests
script: nanomod train -g sample_data/ecoli_k12_mg1655.fa -c sample_data/r9/canonical -m sample_data/r9/modified -t 10 -o sample_data/test -vv
